version: "2"

#volumes:
#  pihole:
#  dnsmasq:

services:
  pihole:
    container_name: pihole_unbound
    image: pihole/pihole:latest
    hostname: PIHOLE_MUMBAI
    ports:
      - "53:53/tcp"
      - "53:53/udp"
#      - "67:67/udp"
      - "8090:8090/tcp"
    networks:
      default:
        ipv4_address: 172.28.0.3
    environment:
      TZ: 'Asia/Kolkata'
      WEBPASSWORD: 'pihole14178971'
      WEB_PORT: 8090
      PIHOLE_DNS_: "172.28.0.2;172.28.0.2"
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq:/etc/dnsmasq.d"
      - "./resolv.conf:/etc/resolv.conf"
#    cap_add:
#      - NET_ADMIN
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    networks:
      default:
        ipv4_address: 172.28.0.2
    healthcheck:
      test: ["CMD", "dig", "-p", "53", "dnssec.works", "@127.0.0.1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    volumes:
      - ./root.hints:/etc/unbound/root.hints
#      - ./unbound.conf.d:/etc/unbound/custom.conf.d

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1
