version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watch_each_day
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 0 * * *"
    restart: always
