services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - ./data:/data
            - ./config:/config
            - ./ovpnconfigs:/etc/openvpn/custom/
        environment:
            - OPENVPN_PROVIDER=custom
            - OPENVPN_CONFIG=nl-free-98.protonvpn.net.udp
            - OPENVPN_USERNAME=
            - OPENVPN_PASSWORD=
            - LOCAL_NETWORK=192.168.0.0/24
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - PGID=1001
            - PUID=1001
        logging:
            driver: json-file
            options:
                max-size: 10m
        #      networks:
        #        - openvpn_network
        ports:
            - 8026:9091
            - 8027:9117
        image: haugene/transmission-openvpn
#    jackett:
#        image: lscr.io/linuxserver/jackett:latest
#        container_name: jackett
#        environment:
#            - PUID=1000
#            - PGID=1000
#            - TZ=Europe/London
#            - AUTO_UPDATE=true #optional
#            - RUN_OPTS=<run options here> #optional
#        volumes:
#            - jackett:/config
#        # You have to comment ports, they should be managed in transmission-openvpn section now.
#       ports:
#           - 9117:9117
#        restart: unless-stopped
#        network_mode: "service:transmission-openvpn" # Add to the transmission-openvpn Container Network
#        depends_on:
#            - transmission-openvpn # Set dependency on transmission-openvpn Container
#        healthcheck: # Here you will check if transmission is reachable from the Jackett container via localhost
#            test: curl -f http://localhost:9091 || exit 1
# Use this test if you protect your transmission with user and password
# comment test above and un-comment line below.
#test: curl -f http://${TRANSMISSION_RPC_USERNAME}:${TRANSMISSION_RPC_PASSWORD}@localhost:9091 || exit 1
#            interval: 5m00s
#            timeout: 10s
#            retries: 2

#volumes:
#  tmovpnconfig:
#  tmovpndata:
#  jackett:

#networks:
#  openvpn_network:
# name: openvpn_tunnel
# driver: custom-driver-1
