version: '3.5'

services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '8095:3001'
    environment:
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
      DASHDOT_ACCEPT_OOKLA_EULA: 'true'
    volumes:
      - /:/mnt/host:ro
